PortfolioProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolioApp import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blogApp.urls')),
    path('about/', include('portfolioApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


blogApp/urls.py

from django.urls import path
from blogApp import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.details, name='details')
]

portfolioApp/urls.py
from django.urls import path
from portfolioApp import views



urlpatterns = [
    path('', views.about, name='about'),
]

blogApp/models.py
from django.db import models


# Create your models here.


class Blog(models.Model):
    

    title = models.CharField(max_length=40)
    date = models.DateField()
    text = models.TextField(max_length=1000)


    def __str__(self):
        return str(self.id) + "." + self.title

portfolioApp/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolioApp/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return str(self.id) + "." + self.title 
        

blogApp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.utils.translation import ngettext

# Create your views here.
def all_blog(request):
    blog = Blog.objects.order_by('-date')[:]
    return render(request, 'blogApp/all_blog.html', {'blog' : blog})


def details(request, blog_id):

    detail_blog = get_object_or_404(Blog, pk=blog_id)
    return render(request,'blogApp/details.html', {'detail_blog': detail_blog})





portfolioApp/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.



def index(request):

    portfolio = Project.objects.all()
    return render(request, 'portfolioApp/index.html', {'portfolio': portfolio})


def about(request):
    return render(request, 'portfolioApp/about.html')

blogApp/templates/blogApp/all_blog.html

{% extends 'portfolioApp/base.html' %}

{% block content %}
    <div class="row justify-content-center mb-3 gx-0">
        <div class="col-md-3 blog"><h1 class="display-5">Blog</h1></div>

        <div class="col-md-6 allblog font detailme" >
            {% for item in blog %}

            <a class="bloglink" href="{% url 'blog:details' item.id %}"><h3 class="line">{{ item.title }}</h3></a>

            {% load i18n %}
            {% language 'en' %}
            <h8 class="font">{{ item.date|date:"M - d Y" }}</h8>
            {% endlanguage %}

            <p class="font">{{ item.text|striptags|truncatechars:70}}</p>  
            <br>
            {% endfor %}
            
        </div>

        <div class="col-md-3 counter">           
            <h5 class="font">Counter: {{ blog.count }} blog{{  blog.count|pluralize:"s" }} </h5>        
        </div>        
    </div>   


{% endblock %}


blogApp/templates/blogApp/details.html

{% extends 'portfolioApp/base.html' %}

{% block content %}

    <div class="row justify-content-center mb-3 gx-0">
        <div class="col-md-8">

            <div class="pb-3 aboutme">
            <h1 class="display-5">{{ detail_blog.title }}</h1>
            </div>

            <div class="col-md-6 font aboutmetext center">
                <br>
                <br>
                <br>
                <br>
                <h3 class="line">{{ item.title }}</h3>
                
                {% load i18n %}
                {% language 'en' %}
                <h8 class="font">{{ detail_blog.date|date:"M - d Y" }}</h8>
                {% endlanguage %}
                
                <p class="font">{{  detail_blog.text|linebreaks }}</p> 
                            
            </div>                    
        </div>         
    </div>



{% endblock %}

portfolioApp/templates/portfolioApp/about.html
{% extends 'portfolioApp/base.html' %}

  {% block content %}

    <div class="row justify-content-center mb-3 gx-0">
      <div class="col-md-8">

        <div class="pb-3 aboutme">
          <h1 class="display-5">About me</h1>
        </div>

        <div class="col-md-6 font aboutmetext center">
            <br>
            <br>
            <h5 class="line">This is something about me: ...</h5>
            <br>
            <p> I worked as a technical worker for the last 10 years. 
              I recently started studying IT and now work as application and system support at Kyndryl.
              In my spare time I am interested in programming. I was most interested in the Python
              programming language due to its simple syntax. I would like to start working on real projects and start
              deepening my knowledge.</p>
                  
            <p>  </p>         
        </div>            
      </div>     
    </div>

  {% endblock %}




portfolioApp/templates/portfolioApp/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tomas portfolio</title>
    <!-- CSS only -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolioApp/custom2.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'portfolioApp/ITnoob2.png' %}">
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark py-3" style="background-color: #35383b;">
      <div class="container-fluid">
          <div class="d-flex flex-grow-1">
              <span class="w-100 d-lg-none d-block">
                  <!-- hidden spacer to center brand on mobile --></span>


                  <ul class="navbar-nav d-flex flex-row me-2 icons">
                    <li class="nav-item me-3 me-lg-0">
                      <a class="nav-link" href="{% url 'index' %}" ><img src="{% static 'portfolioApp/logo_transparent2.png' %}" width="33" height="33" class="d-inline-block align-top" alt=""></a>
                    </li>
                    <li class="nav-item me-3 me-lg-0">
                      <a class="nav-link" href="https://github.com/TomasBalbinder" target=”_blank” ><img src="{% static 'portfolioApp/github4.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
                    </li>
                    <li class="nav-item me-3 me-lg-0">
                      <a class="nav-link" href="https://www.instagram.com/fotograftomasbalbinder/ " target=”_blank” ><img src="{% static 'portfolioApp/instagram.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
                    </li>

                    <li class="nav-item me-3 me-lg-0">
                      <a class="nav-link" href="https://tomasbalbinderphoto.com/" target=”_blank” ><img src="{% static 'portfolioApp/camera3.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""></a>
                    </li>
                  </ul>

              <div class="w-100 text-right">
                  <button class="navbar-toggler icons" type="button" data-bs-toggle="collapse" data-bs-target="#myNavbar">
                      <span class="navbar-toggler-icon"></span>
                  </button>
              </div>
          </div>
          <div class="collapse navbar-collapse flex-grow-3 text-right" id="myNavbar">
              <ul class="navbar-nav ms-auto flex-nowrap">
                  <li class="nav-item">
                      <a href="{% url 'index' %}" class="nav-link m-2 menu-item nav-active">Home</a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'blog:all_blog' %}" class="nav-link m-2 menu-item">Blog</a>
                  </li>
                  <li class="nav-item">
                      <a href="{%  static 'portfolioApp\TomasBalbinderENG.pdf' %}" class="nav-link m-2 menu-item">Resume</a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'about' %}" class="nav-link m-2 menu-item">About me</a>
                  </li>
              </ul>
          </div>
      </div>
    </nav>




{% block content %}


{% endblock %}


  <footer id="footer">
      <div class="container-fluid bg-dark text-light mt-1 pt-1 ">
          <div class="container text-center py-1 font">
              <p style="font-size:13px">Copyright © 2022 All Rights Reserved.</p>
          </div>
      </div>
  </footer>





  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

portfolioApp/templates/portfolioApp/index.html
{% extends 'portfolioApp/base.html' %}

    {% block content %}

    {% load static %}

    <br>
    <br>
    <div class="row justify-content-center mb-3 gx-0">
        <div class="col-md-9 text-center">
        <h1 class="display-5"></h1>
    </div>

    <br>
    <div class="row justify-content-center my-3 gx-0">
        <div class="col-3">

        <a class="nav-link" href="{% static 'portfolioAPP/me.png' %}" ><img src="{% static 'portfolioApp/logo.png' %}" class="img-fluid center" alt="me" ></a>
        </div>
    </div>

    <div class="row gx-0">
        {% for item in portfolio %}
        <div class="col-lg-6 col-md-5 text-center">

            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

            <h3 class="font">{{ item.title }}</h3>

            <p class="font">{{ item.description }}</p>

            {% if item.url %}
            <a target=”_blank” href="{{ item.url }}"><img src="{{ item.image.url }}"  height="200"></a>

            {% else %}
            <img  src="{{ item.image.url }}"  height="200">

            {% endif %}
            <br>
            <br>
            <br>
            <br>

        </div>

        {% endfor %}


    </div>
    {% endblock %}